# Copyright (c) 2022 Robert Bosch GmbH and Microsoft Corporation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        This issue form is for reporting bugs only!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Operating System
      description: What operating system do you use?
      options:
        - macOS (Default)
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What release version or branch did you use?
      description: Please include a link if possible.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our rules for [contribution](https://raw.githubusercontent.com/eclipse-velocitas/vehicle-app-python-sdk/main/CONTRIBUTING.md?token=GHSAT0AAAAAABUFQPIKACAY7TIQMQXGFLJWYUN5AHQ)
      options:
        - label: I agree to follow this project's rules for contributions
          required: true
