/**
 * Copyright (c) 2024-2025 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef VELOCITAS_SERVICE_IMPL_Seats_H
#define VELOCITAS_SERVICE_IMPL_Seats_H

#include "vehicle/Vehicle.hpp"
#include <grpc/grpc.h>
#include <services/seats/seats.grpc.pb.h>

namespace velocitas {

class SeatsService final : public sdv::edge::comfort::seats::v1::Seats::Service {
public:
    SeatsService(){};
    virtual ~SeatsService(){};

    // <auto-generated>
    ::grpc::Status Move(::grpc::ServerContext*                              context,
                        const ::sdv::edge::comfort::seats::v1::MoveRequest* request,
                        ::sdv::edge::comfort::seats::v1::MoveReply*         response) override;
    ::grpc::Status
    MoveComponent(::grpc::ServerContext*                                       context,
                  const ::sdv::edge::comfort::seats::v1::MoveComponentRequest* request,
                  ::sdv::edge::comfort::seats::v1::MoveComponentReply*         response) override;
    ::grpc::Status
    CurrentPosition(::grpc::ServerContext*                                         context,
                    const ::sdv::edge::comfort::seats::v1::CurrentPositionRequest* request,
                    ::sdv::edge::comfort::seats::v1::CurrentPositionReply* response) override;
    // </auto-generated>

private:
    vehicle::Vehicle vehicle;
};

} // namespace velocitas

#include "SeatsServiceImpl.cpp"

#endif // VELOCITAS_SERVICE_IMPL_Seats_H
